### ISSUE TITLE
Deck Lambda Invoke stage has type errors

### ISSUE THREAD

**Issue by jgrumboe** [spinnaker-plugins/aws-lambda-deployment-plugin-spinnaker#63]
Hi,

I want to create a Lambda invoke stage but after selecting an account and region the UI "crashes"/collapses and I cannot edit the stage anymore, only via JSON directly. I'm running Spinnaker 1.23.7.

The console error is: `TypeError: Cannot read property 'data' of undefined`

The screenshot looks like this:
![image](https://user-images.githubusercontent.com/5127047/119523854-65b73800-bd7d-11eb-839d-88be459dc638.png)

Maybe this is somehow linked to #61

**Comment by nimakaviani** [comment]
I had a similar issue, and in my case it was because I didnt enable the `functions` feature in deck.

I solved this by editing `settings-local.js` and adding this line: `window.spinnakerSettings.feature.functions = true` which then allowed the function data to propagate properly in the stage. maybe that is your problem as well?

**Comment by jgrumboe** [comment]
@nimakaviani 
Thanks for the hint. I added the setting but it didn't resolve the error, unfortunately.
The error message is still the same.

**Comment by jgrumboe** [comment]
It's still not working, the error message stays the same. 😢

**Comment by nimakaviani** [comment]
Do you see a `Functions` tab in the red box of picture below?

![image](https://user-images.githubusercontent.com/17132353/119695816-6beff780-be03-11eb-9be3-2f8c5e630e48.png)

**Comment by jgrumboe** [comment]
@nimakaviani No, I think there wasn't a functions menu.

I disabled and undeployed the plugin meanwhile, because I will implement a runjob stage with my aws tasks to be done.
Therefore I will close this issue.
