### ISSUE TITLE
Function names depend on Spinnaker Application name

### ISSUE THREAD

**Issue by eyalmor94** [spinnaker-plugins/aws-lambda-deployment-plugin-spinnaker#69]
This issue is due to how the UI & API interact.

## Reproducing

1. Create a `Lambda Create` stage.
2. Click on the `Edit Stage As JSON` button.
3. Change the `functionUid`, `functionName` to something else (maybe random).
4. Save Pipeline.
5. Execute Pipeline

## Explanation

When setting up a pipeline manually, the `functionName` property is generated via a merge with the application name, used as a name space (js excerpt):
```js
functionName = `${ns}-${fn}`
```
> The implementation is found [here](https://github.com/spinnaker-plugins/aws-lambda-deployment-plugin-spinnaker/blob/a38972e069c2bc1052d87b5a4df98421acc7da2c/lambda-deployment-deck/src/deployLambda/components/BasicSettingsForm.tsx#L37)

Using the application name as a namespace causes automation scripts to become clumsy, weird and will fail when not tailored accurately to the specific usage of the Lambda Plugin.

As an example, the following excerpt is a json that was tailored for function definitions:
```json
{
  "account": "${parameters[\"spinnaker_account\"]}",
  "cloudProvider": "aws",
  "functionName": "${execution.application}-${parameters[\"lambda_function_name\"]}",
  "functionUid": "${parameters[\"lambda_function_name\"]}",
  "type": "Aws.LambdaDeploymentStage"
}
```

This implementation causes multiple issues:

1. the application name takes up a piece of the 64 character limit.
2. Any problem in the `Spel` expression will cause the stage to break.
3. Implementing automation is non trivial, there is no obvious relationship between `functionUid` & `functionName`.

**Comment by shaiguitar** [comment]
I want to re-iterate that although the tailored json example works, I am also running into developer experience problems due to this non-obvious implementation and conflation between `functionUid` and `functionName`.

**Comment by nimakaviani** [comment]
yeah, this makes sense. I dont think we need to tie the function name back to the application name unless chosen by those setting up the pipeline. worst case scenario, colliding function names can be deduped manually by system engineers or based on your stack name etc.

**Comment by gsapkal** [comment]
Spinnaker clouddriver buckets the functions based on resource naming based on application name as prefix. If we remove the function name -> application relation the the caching and filtering would be difficult .

**Comment by gsapkal** [comment]
How spinnaker UI will list the functions for an application ?

**Comment by nimakaviani** [comment]
yes you are right @gsapkal ... looks like namespacing function names is wired down all the way to clouddriver's lambda provider, [here](https://github.com/spinnaker/clouddriver/blob/5cd42ff08aefac0aa157537a993f1c48c48bb84c/clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/cache/Keys.java#L33-L35). 

An unfortunate hard constraint.  If we want to modify the conventions, we probably will have to change it all the way down in the lambda provider as well.

**Comment by nimakaviani** [comment]
application name happens to be the way the clouddriver does the bucketing for the functions of an application. removing application name will break the bucketing and cause lots of issues.
