### ISSUE TITLE
409 Errors cause deployment disruptions - re-run fixes

### ISSUE THREAD

**Issue by eyalmor94** [spinnaker-plugins/aws-lambda-deployment-plugin-spinnaker#72]
There are cases where `409` response is returned from AWS Lambda API.

These cases cause disruption to a deployment.

Observed Cases:
1. `409 Alias Exists` - `AWS Lambda Route $BLUEGREEN`.
2. `409 Function Name Already Exists` - `AWS Lambda Deployment` (during an update)

## Reproducing

There are no clear ways to re-produce these errors as they are intermittent and depend on the AWS API.

**Comment by nimakaviani** [comment]
One issue causing 409 errors was related to the plugin trying to route traffic to a function in a `Pending` state before it becomes `Active`.

This commit: https://github.com/spinnaker-plugins/aws-lambda-deployment-plugin-spinnaker/commit/7d2c9749619b1c22ead711f70220033e491b7229 has introduced a new verification task that waits for the function to become `Active` before trying to route traffic to it.

Did the fix released in v1.0.6 solve your problem, or do you still see errors?

**Comment by eyalmor94** [comment]
@nimakaviani Seems like the caching fixes on Clouddriver did the trick.
Closing the issue.

**Comment by nimakaviani** [comment]
great thanks for the update glad it is working fine now!
