### ISSUE TITLE
Function creation failure may lead to 409 Function Already exists

### ISSUE THREAD

**Issue by eyalmor94** [spinnaker-plugins/aws-lambda-deployment-plugin-spinnaker#73]
When creating a Lambda function via `AWS Lambda Deployment`, the stage may fail for any reason which leads to a missing function in the Spinnaker cache. The failure is ungraceful.

Every subsequent run of the pipeline will fail  with a `409 function already exists`.
The only way to fix this issue it to manually delete the Lambda Function from the AWS console and hope that it will work.

Seems related to - #72 

## Reproducing

Due the intermittent nature of this bug, there are no clear re-production steps. 
Try creating a creating Lambda functions until the bug is re-produced.

**Comment by nimakaviani** [comment]
we should not see any 409 errors in the plugin anymore. feel free to reopen if this happens again.
