### ISSUE TITLE
Event Source Mapping isn't deleted

### ISSUE THREAD

**Issue by eyalle** [spinnaker-plugins/aws-lambda-deployment-plugin-spinnaker#85]
After creating a function, and attaching an ARN for EventSourceMappingsTrigger, everything works as expected.
When re-triggering the job, and removing the ARN, does not remove the attachment (only after another re-run).
This was tested a few times, when triggering without an ARN, we're setting `eventSourceMappings` to an empty list, to verify the mappings are cleared as well.
This still doesn't work on the first run.

some more info:
running version 1.0.6
AWS region = `us-west-2`
Trigger type tested - SQS\Kinesis

---

### Reproducing

1. Run the plugin & create a function using a trigger ARN
2. Re-run the plugin _without_ the ARN from previous step
3. AWS Console should still show the EventTriggering config
4. Re-run the plugin **again without** the ARN from step 1
5. AWS console should show no EventTriggers attached

**Comment by nimakaviani** [comment]
@eyalle can you please confirm that this is still an issue with v1.0.8 of the plugin, and if so we will look into fixing this next.

**Comment by eyalle** [comment]
@nimakaviani I believe this is solved, but we're working on stabilising some of our tests and will be able to run some more extensive tests in the next few days (hopefully)
I _can_ say, that personally I haven't encountered this issue in a some time

**Comment by eyalle** [comment]
@nimakaviani  haven't envountered it so far, closing the issue.
Thank you 🙏

**Comment by nimakaviani** [comment]
thanks for the update!
