### ISSUE TITLE
Environment variables should allow "_" (underscore) in the environment variable name.

### ISSUE THREAD

**Issue by eyalmor94** [spinnaker-plugins/aws-lambda-deployment-plugin-spinnaker#87]
Failing to update environment variables via the plugin when the env variable name contains and `_` character (underscore)
![Pasted_Image_25_07_2021__16_02](https://user-images.githubusercontent.com/9406299/126900026-42be3e9e-78b6-4193-b35c-bd9bf4f29d18.png)

AWS allows this case.
![image](https://user-images.githubusercontent.com/9406299/126900078-2edff1a9-efdb-44da-9a82-db81d7e6420c.png)

# Reproducing

Set `environment variables` to `{"c_c": "c_c"}`.
This will fail the assertion but passes on AWS.

**Comment by nimakaviani** [comment]
- what does the pipeline look like? 
- is it from a second deploy? or an update stage?
- which verification task in the pipeline is failing?

**Comment by nimakaviani** [comment]
np. thanks for the update.
